### ISSUE TITLE
Sonic Adventure 2 Europe CDI

### ISSUE THREAD

**Issue by m3M0ryHuN73R** [Rinnegatamante/flycast-vita-Compatibility#105] opened 2021-01-09 21:20 UTC
# Game summary
- Game name: Sonic Adventure 2
- Game version: CDI

# flycast summary
- Version: v0.1 11822f65
- Downloaded from VHBB

# Issues
Displays Sega and sonic team logos and then crashes.
Dump file info: undefined instruction exception

# Screenshots
![](https://?)

# Recommended labels

- A Crash
- B?
- C?

**Comment by Rinnegatamante** [comment] 2021-01-10 10:38
Duplicate of https://github.com/Rinnegatamante/flycast-vita-Compatibility/issues/46

**Closed by Rinnegatamante** 2021-01-10 10:38 UTC
